export const categoryOptions = [
  "web development",
  "web design",
  "graphic design",
  "mobile development",
  "app development",
  "game development",
  "ui/ux design",
  "data science",
  "data analytics",
  "data visualization",
  "data engineering",
  "data science",
  "data analysis",
  "data analytics",
  "data visualization",
  "data engineering",
  "marketing",
  "business",
  "finance",
  "accounting",
  "marketing",
  "sales",
  "human resources",
  "operations",
  "project management",
  "finance",
  "accounting",
];

export const languageOptions = [
  "english",
  "arabic",
  "french",
  "german",
  "hindi",
  "spanish",
  "russian",
];

export const levelOptions = ["beginner", "intermediate", "advanced"];
